//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class Pi {
    
    // Pin Service for quick reference. Package: Pi Core
    private static PiFramework.PiRoot _root;
    
    public static PiFramework.PiRoot root {
        get {
            if ((_root == null)) {
                _root = serviceLocator.GetService<PiFramework.PiRoot>();
            }
            return _root;
        }
    }
    
    // Pin Service for quick reference. Package: Pi Core
    private static PiFramework.PiApp _app;
    
    public static PiFramework.PiApp app {
        get {
            if ((_app == null)) {
                _app = serviceLocator.GetService<PiFramework.PiApp>();
            }
            return _app;
        }
    }
    
    // Pin Service for quick reference. Package: Pi Core
    private static PiFramework.PiConsole _console;
    
    public static PiFramework.PiConsole console {
        get {
            if ((_console == null)) {
                _console = serviceLocator.GetService<PiFramework.PiConsole>();
            }
            return _console;
        }
    }
    
    // Pin Service for quick reference. Package: Pi Core
    private static PiFramework.PiSystemEvents _systemEvents;
    
    public static PiFramework.PiSystemEvents systemEvents {
        get {
            if ((_systemEvents == null)) {
                _systemEvents = serviceLocator.GetService<PiFramework.PiSystemEvents>();
            }
            return _systemEvents;
        }
    }
    
    // Pin Service for quick reference. Package: Pi Core
    private static PiFramework.PiPlayerPref _playerPref;
    
    public static PiFramework.PiPlayerPref playerPref {
        get {
            if ((_playerPref == null)) {
                _playerPref = serviceLocator.GetService<PiFramework.PiPlayerPref>();
            }
            return _playerPref;
        }
    }
    
    // Pin Service for quick reference. Package: Pi Core
    private static PiFramework.PiProfiler _profiler;
    
    public static PiFramework.PiProfiler profiler {
        get {
            if ((_profiler == null)) {
                _profiler = serviceLocator.GetService<PiFramework.PiProfiler>();
            }
            return _profiler;
        }
    }
}
