//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class Pi {
    
    // Module: Pool Manager
    public static PiFramework.Pool.PoolManager Pool {
        get {
            return Services.GetService<PiFramework.Pool.PoolManager>();
        }
    }
    
    // Module: Simple Sound Player
    public static PiExtension.SimpleSound.SimpleSoundPlayer Audio {
        get {
            return Services.GetService<PiExtension.SimpleSound.SimpleSoundPlayer>();
        }
    }
    
    // Module: Pool Manager 2
    public static PiFramework.Pool.PoolManager test {
        get {
            return Services.GetService<PiFramework.Pool.PoolManager>();
        }
    }
}
