//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class Pi {
    
    // Pin Service for quick reference. Package: Simple Sound Player
    private static PiExtension.SimpleSound.SimpleSoundPlayer _audio;
    
    public static PiExtension.SimpleSound.SimpleSoundPlayer audio {
        get {
            if ((_audio == null)) {
                _audio = services.GetService<PiExtension.SimpleSound.SimpleSoundPlayer>();
            }
            return _audio;
        }
    }
}
